fit:
    seed_everything: 42
    trainer:
        default_root_dir: fashion_mnist_conv_gpu
        max_epochs: 20
        max_time: null             
        profiler: 'advanced' 
        accelerator: 'gpu'
        devices: 1
        num_nodes: 1
        precision: 32                                                  
        logger:                                                         
          - class_path: lightning.pytorch.loggers.TensorBoardLogger      
            init_args:                                                    
                save_dir: fashion_mnist_conv_gpu
                name: tensorboard                                             
                version: ''                                                    
        benchmark: false                                                      
        enable_checkpointing: true                                             
        callbacks:                                                              
          - class_path: lightning.pytorch.callbacks.LearningRateMonitor          
            init_args:                                                            
                logging_interval: epoch                                              
                log_momentum: false                                                   
          - class_path: lightning.pytorch.callbacks.ModelCheckpoint 
            init_args:                                
                dirpath: fashion_mnist_conv_gpu
                monitor: validation_loss                  
                save_top_k: -1                             
                every_n_epochs: 1                           
                filename: '{epoch}-{validation_loss:.4f}'    
                save_last: true      
        log_every_n_steps: 1      
        gradient_clip_val: 0         
        gradient_clip_algorithm: norm 
        check_val_every_n_epoch: 1
        fast_dev_run: false 
        accumulate_grad_batches: 1 
        enable_model_summary: false  
        deterministic: false
        num_sanity_val_steps: -1
    optimizer:
        class_path: torch.optim.Adam
        init_args:
            lr: 0.001
    lr_scheduler: null
    model:
        class_path: pytorch_hpc.pl.pl_model.LightningModel
        init_args:
            task: 'multiclass'
            model:
                class_path: pytorch_hpc.nn.models.ConvolutionClassifier
                init_args:
                    in_dim: 2304
                    out_dim: 10
                    in_channels: 1
                    conv_channels: [64,64]
                    conv_kernels: [2,2]
                    pooling_kernels: [2,2]
                    activation:
                        class_path: torch.nn.ReLU
                    hidden_layers: [1024,512,256]
            loss_function:
                class_path: torch.nn.CrossEntropyLoss
                init_args:
                    reduction: mean
    data:
        class_path: pytorch_hpc.pl.pl_data.TorchvisionDataModule
        init_args:
            dataset_name: "FashionMNIST"
            root_dir: /scratch/usr/bzfbnick/pytorch_hpc_output/local_datasets
            splits_fn: null
            train_dataloader_opts:
                batch_size: 512
                shuffle: true
                num_workers: 2
                pin_memory: true
            val_dataloader_opts:
                batch_size: 512
                shuffle: false
                num_workers: 2
                pin_memory: true
            test_dataloader_opts:
                batch_size: 512
                shuffle: false
                pin_memory: true
            transform:
                - ToTensor
